Repository Kraks/sai, pull requests merged in 2022-03, with the labels that each got.

#61 bug fix on enginebase
  dev-clean/src/main/scala/sai/llsc/EngineBase.scala
Labels: bug

#59 Add klee POSIX runtime file system support, add va_arg support
  .github/workflows/scala.yml
  dev-clean/benchmarks/external_lib/read2.c
  dev-clean/benchmarks/external_lib/stat2.c
  dev-clean/benchmarks/klee_fs_lib/FreeBSD.h
  dev-clean/benchmarks/klee_fs_lib/LICENSE.TXT
  dev-clean/benchmarks/klee_fs_lib/Makefile
  dev-clean/benchmarks/klee_fs_lib/fd.c
  dev-clean/benchmarks/klee_fs_lib/fd.h
  dev-clean/benchmarks/klee_fs_lib/fd_32.c
  dev-clean/benchmarks/klee_fs_lib/fd_64.c
  dev-clean/benchmarks/klee_fs_lib/fd_init.c
  dev-clean/benchmarks/klee_fs_lib/illegal.c
  dev-clean/benchmarks/klee_fs_lib/klee_init_env.c
  dev-clean/benchmarks/klee_fs_lib/llsc.c
  dev-clean/benchmarks/klee_fs_lib/misc.c
  dev-clean/benchmarks/klee_fs_lib/selinux.c
  dev-clean/benchmarks/klee_fs_lib/stubs.c
  dev-clean/benchmarks/klee_fs_lib/test.c
  dev-clean/benchmarks/llvm/argv1.c
  dev-clean/benchmarks/llvm/argv2.c
  dev-clean/benchmarks/llvm/varArgInt.c
  dev-clean/headers/llsc.hpp
  dev-clean/headers/llsc/external_imp.hpp
  dev-clean/headers/llsc/external_pure.hpp
  dev-clean/headers/llsc/external_shared.hpp
  dev-clean/headers/llsc_client.h
  dev-clean/src/main/scala/sai/lang/Benchmarks.scala
  dev-clean/src/main/scala/sai/llsc/EngineBase.scala
  dev-clean/src/main/scala/sai/llsc/states/GenericDefs.scala
  dev-clean/src/test/scala/sai/llsc/TestLLSC.scala
Labels: enhancement

#60 using multiple queues in tp
  dev-clean/headers/llsc/thread_pool.hpp
  dev-clean/headers/sai.hpp
  dev-clean/src/test/scala/sai/llsc/TestLLSC.scala
Labels: enhancement

#57 using const ptrval ref
  dev-clean/headers/llsc/state_pure.hpp
  dev-clean/headers/llsc/value_ops.hpp
Labels: performance

#54 rewritings for kmp
  dev-clean/src/main/scala/sai/llsc/Codegen.scala
  dev-clean/src/main/scala/sai/llsc/states/GenericDefs.scala
  dev-clean/src/test/scala/sai/llsc/TestLLSC.scala
Labels: performance

#66 parameterize the number of queues
  dev-clean/headers/llsc/auxiliary.hpp
  dev-clean/headers/llsc/cli.hpp
  dev-clean/headers/llsc/thread_pool.hpp
  dev-clean/src/main/scala/sai/lang/LLVM.scala
  dev-clean/src/main/scala/sai/llsc/engines/PureCPSEngine.scala
  dev-clean/src/main/scala/sai/llsc/states/SymExeState.scala
Labels: enhancement

#63 save generating functions from some deterministic jump
  dev-clean/src/main/scala/sai/llsc/EngineBase.scala
  dev-clean/src/main/scala/sai/llsc/engines/CPSEngine.scala
  dev-clean/src/main/scala/sai/llsc/engines/Engine.scala
  dev-clean/src/main/scala/sai/llsc/engines/ImpEngine.scala
  dev-clean/src/main/scala/sai/llsc/engines/PureCPSEngine.scala
  dev-clean/src/main/scala/sai/llsc/states/SymExeState.scala
  dev-clean/src/test/scala/sai/llsc/TestLLSC.scala
Labels: performance
